#!/bin/bash
# ------------------------------------------------------------------
#
#  Scripts/updcount
#  Description: Script for checking the number of updates available
#  Author: Alex Sánchez <kniren@gmail.com>
#
# ------------------------------------------------------------------

ICON="pacman.xbm"
NUMBER=`dpkg -l | wc -l`

ICON='^i(/home/ritzr0czka/.xmonad/dzen/icons/xbm8x8/'"$ICON)"
echo "$ICON $NUMBER"
